spring.application.name=demoOCP
server.port=8080

# Expose health endpoints
management.endpoints.web.exposure.include=health

# Expose dedicated probe endpoints
management.endpoint.health.probes.enabled=true

# Keep details limited (optional but recommended)
management.endpoint.health.show-details=never
